<a href="https://colab.research.google.com/github/EduEnthusiast/my-practice-from-colab-notebook/blob/main/my_own_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
#1 dimentional series
mobile = pd.Series(["samsung" , "iphone" , "Nokia"])
mobile

0    samsung
1     iphone
2      Nokia
dtype: object

In [ ]:
my_bag = pd.Series(["pen" , "notebook" , "laptop"])
my_bag

0         pen
1    notebook
2      laptop
dtype: object

In [ ]:
#lets write 2 dimensional dataframe ,  it takes dictionary then list
dataframe = pd.DataFrame({"electronics":mobile , "items":my_bag})
dataframe

  electronics     items
0     samsung       pen
1      iphone  notebook
2       Nokia    laptop

In [ ]:
data={
    'Name':['Tom','nick','krish','jack'],
    'Age':[20,21,19,18],
    "city":["New York" , "Los Angeles" , "Japan", "Chicago"],
    "Marks":[50 , 60 , 70 , 80 ]
    }
df=pd.DataFrame(data)
df

    Name  Age         city  Marks
0    Tom   20     New York     50
1   nick   21  Los Angeles     60
2  krish   19        Japan     70
3   jack   18      Chicago     80

In [ ]:
phone_csv = pd.read_csv("mobile_data.csv")
phone_csv

   ID    Brand          Model  Price (PKR) Storage
0   1  Samsung            A32        55000   128GB
1   2    Apple      iPhone 13       180000   128GB
2   3   Xiaomi  Redmi Note 12        45000   128GB
3   4     Oppo            A57        39000    64GB
4   5     Vivo            Y21        35000    64GB
5   6   Realme            C35        32000   128GB
6   7  Infinix         Hot 12        30000    64GB
7   8    Tecno        Spark 9        28000    64GB
8   9  OnePlus       Nord CE2        62000   128GB

In [ ]:
phone_csv.to_csv(" Modified_phones_v1.csv", index = False)
phone_csv = pd.read_csv(" Modified_phones_v1.csv")
phone_csv

   ID    Brand          Model  Price (PKR) Storage
0   1  Samsung            A32        55000   128GB
1   2    Apple      iPhone 13       180000   128GB
2   3   Xiaomi  Redmi Note 12        45000   128GB
3   4     Oppo            A57        39000    64GB
4   5     Vivo            Y21        35000    64GB
5   6   Realme            C35        32000   128GB
6   7  Infinix         Hot 12        30000    64GB
7   8    Tecno        Spark 9        28000    64GB
8   9  OnePlus       Nord CE2        62000   128GB

how to describe the data
by using attributes which are not followd by ()

In [ ]:
phone_csv.dtypes

ID              int64
Brand          object
Model          object
Price (PKR)     int64
Storage        object
dtype: object

In [ ]:
phone_csv.columns

Index(['ID', 'Brand', 'Model', 'Price (PKR)', 'Storage'], dtype='object')

In [ ]:
phone_csv.index

RangeIndex(start=0, stop=9, step=1)

In [ ]:
phone_csv.describe()

             ID    Price (PKR)
count  9.000000       9.000000
mean   5.000000   56222.222222
std    2.738613   47827.235384
min    1.000000   28000.000000
25%    3.000000   32000.000000
50%    5.000000   39000.000000
75%    7.000000   55000.000000
max    9.000000  180000.000000

In [ ]:
phone_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           9 non-null      int64
 1   Brand        9 non-null      object
 2   Model        9 non-null      object
 3   Price (PKR)  9 non-null      int64
 4   Storage      9 non-null      object
dtypes: int64(2), object(3)
memory usage: 492.0+ bytes

In [ ]:
test=pd.Series([1,2,3,4,5])
test.mean()

np.float64(3.0)

In [ ]:
phone_csv["Brand"].sum()

'SamsungAppleXiaomiOppoVivoRealmeInfinixTecnoOnePlus'

In [ ]:
phone_csv["Price (PKR)"].sum()

np.int64(506000)

### Data selection

In [ ]:
phone_csv

   ID    Brand          Model  Price (PKR) Storage
0   1  Samsung            A32        55000   128GB
1   2    Apple      iPhone 13       180000   128GB
2   3   Xiaomi  Redmi Note 12        45000   128GB
3   4     Oppo            A57        39000    64GB
4   5     Vivo            Y21        35000    64GB
5   6   Realme            C35        32000   128GB
6   7  Infinix         Hot 12        30000    64GB
7   8    Tecno        Spark 9        28000    64GB
8   9  OnePlus       Nord CE2        62000   128GB

In [ ]:
phone_csv.head()

   ID    Brand          Model  Price (PKR) Storage
0   1  Samsung            A32        55000   128GB
1   2    Apple      iPhone 13       180000   128GB
2   3   Xiaomi  Redmi Note 12        45000   128GB
3   4     Oppo            A57        39000    64GB
4   5     Vivo            Y21        35000    64GB

In [ ]:
phone_csv.head(8)

   ID    Brand          Model  Price (PKR) Storage
0   1  Samsung            A32        55000   128GB
1   2    Apple      iPhone 13       180000   128GB
2   3   Xiaomi  Redmi Note 12        45000   128GB
3   4     Oppo            A57        39000    64GB
4   5     Vivo            Y21        35000    64GB
5   6   Realme            C35        32000   128GB
6   7  Infinix         Hot 12        30000    64GB
7   8    Tecno        Spark 9        28000    64GB

In [ ]:
phone_csv.tail()

   ID    Brand     Model  Price (PKR) Storage
4   5     Vivo       Y21        35000    64GB
5   6   Realme       C35        32000   128GB
6   7  Infinix    Hot 12        30000    64GB
7   8    Tecno   Spark 9        28000    64GB
8   9  OnePlus  Nord CE2        62000   128GB

# **index or location**
index is known as (.loc)
location is known as (.iloc)

In [ ]:
birds=pd.Series(["crow","pigion","parrot","wingedDonkey","eagle" ] , index=[2,4,6,8,10])
birds

2             crow
4           pigion
6           parrot
8     wingedDonkey
10           eagle
dtype: object

In [ ]:
birds.loc[8]

'wingedDonkey'

In [ ]:
birds.iloc[3]

'wingedDonkey'